version: "3"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    volumes: 
      - .:/code
    depends_on:
      - db_postgres
    
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - /home/haza/docker/api/backend/static:/code/static
      - /home/haza/docker/api/backend/media:/code/media
    depends_on:
      - django_app

volumes:
  .:
  postgres_data:
  
        
