# Generated by Django 3.1.7 on 2021-04-09 11:46

from django.db import migrations, models
import django.db.models.deletion
import tareas.models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'nombre',
                'verbose_name_plural': 'tareas2',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tareas.models.get_image_filename)),
                ('tarea', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tareas.tareas2')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
    ]
